# Namespace: career-coach
apiVersion: v1
kind: Namespace
metadata:
  name: career-coach

---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: career-coach-secret
  namespace: career-coach
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL01hdmVyaWNrJTIwQ29kZXJzOm5wZ19telRQeW5LWk1yNjBAZXAtcXVpZXQtcGluZS1hODg2eWxiZy1wb29sZXIuZWFzdHVzMi5henVyZS5uZW9uLnRlY2gvc2Vuc2FpP3NzbG1vZGU9cmVxdWlyZQ==
  CLERK_SECRET_KEY: c2tfdGVzdF9lOUllY1ZlNzFrV0V0ZFQ5cm1mVXV3TVU3bmdGSWY4YnBTZDhDbE52N2I=
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: cGtfdGVzdF9hVzUwWlc1elpTMXRhVzVyTFRRMExtTnNaWEpyTG1GalkyOTFiblJ6TG1SbGRpUQ==
  GEMINI_API_KEY: QUl6YVN5RFUxajluX19UbnFBZV8ybEdJRXBVbnp2SHBjVnhUSWZZ

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: career-coach-deployment
  namespace: career-coach
spec:
  replicas: 2
  #revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: career-coach
  template:
    metadata:
      name: career-coach-frontend-pod
      labels:
        app: career-coach
    spec:
      serviceAccountName: career-coach-sa
      containers:
      - name: career-coach-frontend
        image: shubhankar24/career-coach:V4.5
        resources:      # Resource Quotas for limitation of CPU and Memory Usage
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: career-coach-secret
                key: DATABASE_URL

          - name: CLERK_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: career-coach-secret
                key: CLERK_SECRET_KEY

          - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            valueFrom:
              secretKeyRef:
                name: career-coach-secret
                key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: career-coach-secret
                key: GEMINI_API_KEY
