apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: career-coach-hpa
  namespace: career-coach
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: career-coach-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
