apiVersion: v1
kind: ServiceAccount
metadata:
  name: career-coach-sa
  namespace: career-coach

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: career-coach-role
  namespace: career-coach
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: career-coach-rolebinding
  namespace: career-coach
subjects:
  - kind: ServiceAccount
    name: career-coach-sa
    namespace: career-coach
roleRef:
  kind: Role
  name: career-coach-role
  apiGroup: rbac.authorization.k8s.io
